### ISSUE TITLE
About the unpublished Dependency

### ISSUE THREAD

**Issue by ghost** [DylanRJohnston/simon_says#1]
In Cargo.toml, we can see these 2 lines
```toml
bevy_firework = { path = "../../github/bevy_firework" }
bevy_video_glitch = { path = "../../github//bevy_video_glitch" }
```
But they are not vendored along with the project.
Would what patch did the project use be pointed out?
